global_config:
  seed: 1441
  device: cpu
  is_mp: True
  is_dp: False # is differential private
  save_cm: False
---
data_config:
  datasets_names: ["bloodmnist", "organamnist", "pathmnist"]
  data_path: "./data/"
  iid: False
  task: "multi-class"
  mgn: 3 # Max grad norm for the Privacy Engine
---
fed_config:
  C: 0.8
  K: [2]
  R: 30
  E: 10
  B: 32
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.Adam
---
optim_config:
  lr: 0.0005
  scheduler:
    type: "CosineAnnealingLR"
    T_max: 15
---
init_config:
  init_type: "normal"
  init_gain: 1.0
  gpu_ids: [0]
---
model_config:
  name: Qfnn
  channels: [3, 1, 3]
  classes: [8, 11, 9]
  n_qubits: 3
  n_fuzzy_mem: 3
  hidden_layers: [128, 64]
  dropout: 0.3
---
log_config:
  log_path: "./log_meaningful_name/"
  log_name: "FL.log"
  tb_port: 5252
  tb_host: "0.0.0.0"
---
traditional_config:
  R: 100
  B: 32
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.Adam