global_config:
  seed: 1441
  device: "cuda"
  is_mp: True
  is_dp: False # is differential private
  save_cm: False
---
data_config:
  datasets_names: ["bloodmnist", "organamnist"]
  data_path: "./data/"
  num_shards: 4
  iid: False
  task: "multi-class"
  mgn: 3 # Max grad norm for the Privacy Engine
---
fed_config:
  C: 1.0 # fraction
  K: [2] # num_clients, accepts a list as in [2, 8, 12, 32]
  R: 1 # num_rounds
  E: 1 # local_epochs
  B: 64 # batch_size
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.Adam
---
optim_config:
  lr: 0.001
---
init_config:
  init_type: "normal"
  init_gain: 1.0
  gpu_ids: [0]
---
model_config:
  name: CustomResNet
  channels: [3, 1, 3]
  classes: [8, 11, 9]
---
log_config:
  log_path: "./log_meaningful_name/"
  log_name:  "FL.log"
  tb_port: 5252
  tb_host: "0.0.0.0"
---
traditional_config:
  R: 100 # num_rounds
  B: 64 # batch_size
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.Adam